// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA32MoPafTy4pnM0O4oOo6M4rnAYNx_QQ',
    appId: '1:878207584609:android:32d17d55910825d6255d20',
    messagingSenderId: '878207584609',
    projectId: 'lanlan-b8ada',
    storageBucket: 'lanlan-b8ada.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCn6qDA1aO_T07FOP8ruICZLg6ps_Ol_MU',
    appId: '1:878207584609:ios:f80e1bf472378beb255d20',
    messagingSenderId: '878207584609',
    projectId: 'lanlan-b8ada',
    storageBucket: 'lanlan-b8ada.appspot.com',
    iosClientId: '878207584609-g7dpqqvpp3o3ooolfvpr400vpcgub1sl.apps.googleusercontent.com',
    iosBundleId: 'com.example.lanlan',
  );
}
